# Run the nightly build on the future branch because scheduled
# workflows run only on the default branch and that's not future.
on:
    workflow_dispatch:
    schedule:
        - cron: "26 8 1 1,4,7,10 *"

jobs:
    call-workflow:
        if: github.event_name == 'workflow_dispatch' || github.repository == 'gnucash/gnucash-on-windows'
        uses: gnucash/gnucash-on-windows/.github/workflows/build-ucrt64-guile3.yml@future